from .stdc_head import STDCHead
from .decode_head import BaseDecodeHead
from .polyp_head import PolypHead
from .dla_head import DLAHead
from .ocr_head import OCRHead
from .fcn_head import FCNHead
from .segformer_head import SegformerHead
from .sta_head import STAHead
from .pra_head import PRAHead
from .align_head import AlignHead
from .stdc_head import STDCSimple
